In [2]:
import pandas as pd 

activity = pd.read_csv('BigContest/train_activity.csv')
combat = pd.read_csv('BigContest/train_combat.csv')
label = pd.read_csv('BigContest/train_label.csv')
payment = pd.read_csv('BigContest/train_payment.csv')
pledge = pd.read_csv('BigContest/train_pledge.csv')
trade = pd.read_csv('BigContest/train_trade.csv')

In [3]:
combat.head()

,day,acc_id,char_id,server,class,level,pledge_cnt,random_attacker_cnt,random_defender_cnt,temp_cnt,same_pledge_cnt,etc_cnt,num_opponent
0,1,13809,54861,ap,2,13,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
1,1,13809,256332,ap,2,13,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
2,1,13809,307293,ap,3,14,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000
3,1,13809,374964,ap,7,16,0.0,0.0,0.0,0.0,0.0,0.112612,0.098129
4,1,13809,117917,ap,2,11,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000

In [4]:
combat.dtypes

day                      int64
acc_id                   int64
char_id                  int64
server                  object
class                    int64
level                    int64
pledge_cnt             float64
random_attacker_cnt    float64
random_defender_cnt    float64
temp_cnt               float64
same_pledge_cnt        float64
etc_cnt                float64
num_opponent           float64
dtype: object

In [34]:
jobs_class=['king','knight','fairy','wizard','Delf','dragonK','witch','fighter'] # 만들고자 하는 df 변수명리스트
for i,v in enumerate(jobs_class): # i:변수명 리스트 index , v: 변수명 리스트 value
      globals()[v] = combat[combat['class']==i ]

In [33]:
knight

,day,acc_id,char_id,server,class,level,pledge_cnt,random_attacker_cnt,random_defender_cnt,temp_cnt,same_pledge_cnt,etc_cnt,num_opponent
7,1,62835,179366,am,1,14,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
18,1,16629,149458,ae,1,6,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
19,1,10931,236388,an,1,17,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
22,1,115006,21515,bd,1,12,0.000000,0.0,0.000000,0.000000,0.0,1.013504,0.785030
27,1,128300,187302,av,1,17,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
28,1,74305,343563,an,1,17,2.310633,0.0,0.000000,0.000000,0.0,14.526887,1.864446
30,1,74305,343563,bn,1,17,0.000000,0.0,0.000000,0.000000,0.0,0.675669,0.490644
32,1,77519,176073,ae,1,14,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
36,1,66631,397337,ai,1,17,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
37,1,104613,183473,am,1,11,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
39,1,127811,353116,az,1,9,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
42,1,127811,196677,bb,1,6,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
44,1,27245,165282,az,1,17,0.000000,0.0,0.000000,0.479728,0.0,0.112612,0.196258
60,1,53790,24948,ax,1,16,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
68,1,99016,43078,ab,1,17,0.000000,0.0,2.366129,0.000000,0.0,0.112612,0.294386
69,1,19235,232018,ae,1,17,0.449290,0.0,0.000000,0.000000,0.0,0.112612,0.785030
70,1,124411,330951,aq,1,17,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
71,1,124411,304481,aw,1,17,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
72,1,124411,154274,aq,1,1,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
74,1,113033,387865,ap,1,0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
76,1,72408,285602,ak,1,14,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
78,1,101435,176661,aj,1,17,0.962764,0.0,0.000000,0.000000,0.0,0.112612,1.570060
79,1,101435,176661,bm,1,17,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
80,1,103461,134252,bc,1,16,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
81,1,54521,29747,ad,1,11,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
90,1,111208,195742,ac,1,17,4.300344,0.0,0.000000,0.000000,0.0,0.337835,5.004566
99,1,9090,322284,ax,1,0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
100,1,77062,360400,an,1,0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
106,1,64887,299391,aj,1,14,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
122,1,98734,323588,ar,1,16,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1574347,10,22806,48820,aw,1,14,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574383,10,49628,204157,au,1,3,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574384,10,49628,167948,ao,1,3,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574385,10,49628,342567,af,1,3,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574386,10,127840,142160,af,1,3,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574387,10,127840,113259,au,1,3,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574388,10,127840,30668,ao,1,3,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574408,10,127038,282056,at,1,2,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574409,10,13386,394998,af,1,2,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574410,10,13386,62600,ao,1,2,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574411,10,13386,275148,ay,1,2,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574433,10,120433,213853,am,1,0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574435,10,108862,54995,as,1,2,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574437,10,85951,367814,bc,1,12,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574441,10,82174,359353,ac,1,17,0.000000,0.0,0.000000,0.000000,0.0,0.112612,0.098129
1574444,10,121371,210625,an,1,2,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574449,10,49046,246308,aa,1,2,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574453,10,107893,113510,bd,1,15,1.155316,0.0,0.000000,0.000000,0.0,11.936822,8.537202
1574477,10,82822,175991,ao,1,0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574491,10,59425,201314,bc,1,16,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574502,10,77965,274553,am,1,2,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574516,10,35388,261877,bd,1,6,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574529,10,61951,129664,ar,1,14,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574531,10,120204,329019,ax,1,16,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574554,10,16912,332261,bc,1,15,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574558,10,13227,96622,bc,1,16,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574582,10,59435,99896,ae,1,2,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574629,10,87077,381584,ao,1,1,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574635,10,61285,11380,an,1,6,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000
1574664,10,99635,254772,av,1,2,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000