In [2]:
import pandas as pd

In [3]:
act = pd.read_csv('../BigconData/train_activity.csv')

In [4]:
act.head()

,day,acc_id,char_id,server,playtime,npc_kill,solo_exp,party_exp,quest_exp,rich_monster,death,revive,exp_recovery,fishing,private_shop,game_money_change,enchant_count
0,1,75001,397380,aa,1.441844,0.000000,0.000000,0.000000,0.000000,0,0.000000,0.000000,0.0,0.0,1.10514,0.034006,0.0
1,1,75001,216231,aa,0.283219,2.247978,0.047085,0.000000,0.000000,0,0.000000,0.000000,0.0,0.0,0.00000,-0.013963,0.0
2,1,75711,308769,aa,1.036910,2.956638,0.321821,0.166593,0.003470,1,0.245883,0.247337,0.0,0.0,0.00000,-0.001987,0.0
3,1,72230,387177,aa,0.229384,4.042102,0.099147,0.000000,0.001735,0,0.000000,0.000000,0.0,0.0,0.00000,-0.028884,0.0
4,1,34253,339862,aa,1.088405,0.596802,0.003377,0.000000,0.000000,0,0.000000,0.000000,0.0,0.0,0.00000,0.011777,0.0

In [5]:
act.describe()[['playtime','npc_kill','solo_exp','party_exp','quest_exp','rich_monster','death','revive','exp_recovery','fishing','private_shop','game_money_change','enchant_count']]

,playtime,npc_kill,solo_exp,party_exp,quest_exp,rich_monster,death,revive,exp_recovery,fishing,private_shop,game_money_change,enchant_count
count,1.601834e+06,1.601834e+06,1.601834e+06,1.601834e+06,1.601834e+06,1.601834e+06,1.601834e+06,1.601834e+06,1.601834e+06,1.601834e+06,1.601834e+06,1.601834e+06,1.601834e+06
mean,1.043823e+00,4.947465e-01,2.333977e-01,1.290938e-01,1.056613e-01,1.233842e-01,7.406203e-02,6.628034e-02,5.687179e-02,1.937402e-01,2.628405e-01,-1.301906e-03,1.621690e-02
std,1.205552e+00,1.120514e+00,1.236795e+00,1.102296e+00,1.092334e+00,3.288778e-01,7.261568e-01,7.245752e-01,1.005399e+00,5.764657e-01,8.199551e-01,8.827070e-01,8.780636e-01
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-8.478808e+01,0.000000e+00
25%,3.979114e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.335242e-03,0.000000e+00
50%,4.517465e-01,3.379401e-03,2.315290e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,1.764854e+00,3.463886e-01,2.178079e-02,0.000000e+00,8.676596e-04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.030153e-03,0.000000e+00
max,3.370544e+00,1.786622e+01,6.932613e+01,1.064465e+02,3.602985e+01,1.000000e+00,2.215410e+02,2.228505e+02,7.974367e+01,3.370544e+00,3.370544e+00,7.386443e+01,1.888458e+02

In [6]:
act.describe().loc['mean'][['playtime','npc_kill','solo_exp','party_exp','quest_exp','rich_monster','death','revive','exp_recovery','fishing','private_shop','game_money_change','enchant_count']]

playtime             1.043823
npc_kill             0.494747
solo_exp             0.233398
party_exp            0.129094
quest_exp            0.105661
rich_monster         0.123384
death                0.074062
revive               0.066280
exp_recovery         0.056872
fishing              0.193740
private_shop         0.262841
game_money_change   -0.001302
enchant_count        0.016217
Name: mean, dtype: float64

In [7]:
act_mean = act.describe()[1:2][['playtime','npc_kill','solo_exp','party_exp','quest_exp','rich_monster','death','revive','exp_recovery','fishing','private_shop','game_money_change','enchant_count']]
act_mean

,playtime,npc_kill,solo_exp,party_exp,quest_exp,rich_monster,death,revive,exp_recovery,fishing,private_shop,game_money_change,enchant_count
mean,1.043823,0.494747,0.233398,0.129094,0.105661,0.123384,0.074062,0.06628,0.056872,0.19374,0.262841,-0.001302,0.016217

In [8]:
act_std = act.describe()[2:3][['playtime','npc_kill','solo_exp','party_exp','quest_exp','rich_monster','death','revive','exp_recovery','fishing','private_shop','game_money_change','enchant_count']]
act_std

,playtime,npc_kill,solo_exp,party_exp,quest_exp,rich_monster,death,revive,exp_recovery,fishing,private_shop,game_money_change,enchant_count
std,1.205552,1.120514,1.236795,1.102296,1.092334,0.328878,0.726157,0.724575,1.005399,0.576466,0.819955,0.882707,0.878064

In [9]:
act_std_mul = act_std*2
upper = act_mean.iloc[0].add(act_std_mul.iloc[0]) #Upper limit
upper

playtime             3.454926
npc_kill             2.735774
solo_exp             2.706987
party_exp            2.333685
quest_exp            2.290330
rich_monster         0.781140
death                1.526376
revive               1.515431
exp_recovery         2.067669
fishing              1.346672
private_shop         1.902751
game_money_change    1.764112
enchant_count        1.772344
dtype: float64

In [10]:
lower= act_mean.iloc[0].sub(act_std_mul.iloc[0]) #Lower limit
lower

playtime            -1.367280
npc_kill            -1.746281
solo_exp            -2.240191
party_exp           -2.075497
quest_exp           -2.079007
rich_monster        -0.534371
death               -1.378252
revive              -1.382870
exp_recovery        -1.953926
fishing             -0.959191
private_shop        -1.377070
game_money_change   -1.766716
enchant_count       -1.739910
dtype: float64

In [11]:
scope = pd.DataFrame({'upperLimit':upper,'lowerLimit':lower}).T
scope

,playtime,npc_kill,solo_exp,party_exp,quest_exp,rich_monster,death,revive,exp_recovery,fishing,private_shop,game_money_change,enchant_count
upperLimit,3.454926,2.735774,2.706987,2.333685,2.290330,0.781140,1.526376,1.515431,2.067669,1.346672,1.902751,1.764112,1.772344
lowerLimit,-1.367280,-1.746281,-2.240191,-2.075497,-2.079007,-0.534371,-1.378252,-1.382870,-1.953926,-0.959191,-1.377070,-1.766716,-1.739910

In [12]:
# 테스트 데이터가 유효범위에 70% 이상 포함되는지 확인하자

In [13]:
test_act_raw = pd.read_csv('../BigconData/test1_activity.csv')
test_act = test_act_raw

In [23]:
test_act[(test_act['playtime']<=scope.iloc[0]['playtime']) & (test_act['playtime']>=scope.iloc[1][ 'playtime'])]['playtime'].count()

709928

In [22]:
test_act['playtime'].count()

709928

In [19]:
# test1의 전체 row 수는 709928
#709928 모두가 범위에 포함되므로 낙찰!

In [24]:
cols = ['playtime','npc_kill','solo_exp','party_exp','quest_exp','rich_monster','death','revive','exp_recovery','fishing','private_shop','game_money_change','enchant_count']
for col in cols:
    print(col)
    print(test_act[(test_act[col]<=scope.iloc[0][col]) & (test_act[col]>=scope.iloc[1][col])][col].count()/test_act[col].count())

playtime
1.0
npc_kill
0.9595325159734508
solo_exp
0.9972236621178485
party_exp
0.9985181595880146
quest_exp
0.9925034651401269
rich_monster
0.9197439740368037
death
0.9925936151271678
revive
0.9932486111267621
exp_recovery
0.9965334512795664
fishing
0.9446464993633157
private_shop
0.9355258561431582
game_money_change
0.9796331458964853
enchant_count
0.9997196898840446

In [25]:
# activity 끝
# 아니.. test2 activitu도 해야한다

In [27]:
test2_act_raw = pd.read_csv('../BigconData/test2_activity.csv')
test2_act = test2_act_raw
test_act = test2_act_raw

In [29]:
cols = ['playtime','npc_kill','solo_exp','party_exp','quest_exp','rich_monster','death','revive','exp_recovery','fishing','private_shop','game_money_change','enchant_count']
for col in cols:
    print(col)
    print(test_act[(test_act[col]<=scope.iloc[0][col]) & (test_act[col]>=scope.iloc[1][col])][col].count()/test_act[col].count())

playtime
1.0
npc_kill
0.9628344323575119
solo_exp
0.9844045318997018
party_exp
0.9771462472174388
quest_exp
0.9909369881137385
rich_monster
0.9336057268259902
death
0.9895719580830779
revive
0.9900746566424461
exp_recovery
0.9970861858960897
fishing
0.9567994245873409
private_shop
0.9487982485614683
game_money_change
0.9796649901297828
enchant_count
0.9995471775379058

In [30]:
# test2 또한 굿
# 0.7이하가 없네